### ISSUE TITLE
no suitable image found error

### ISSUE THREAD

**Issue by jayshepherd** [pbhogan/scrypt#36]
Since moving to Yosemite, I've been getting the following error with Scrypt 1.2.1 and 2.0.0. Any ideas?

```
/Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/ffi-1.9.3/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library '/Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle': dlopen(/Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/ext/scrypt/x86_64
-darwin/libscrypt_ext.bundle, 5): no suitable image found.  Did find: (LoadError)
        /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle: mach-o, but wrong architecture
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/ffi-1.9.3/lib/ffi/library.rb:100:in `map'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/ffi-1.9.3/lib/ffi/library.rb:100:in `ffi_lib'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/lib/scrypt/scrypt_ext.rb:7:in `<module:Ext>'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/lib/scrypt/scrypt_ext.rb:5:in `<module:SCrypt>'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/lib/scrypt/scrypt_ext.rb:4:in `<top (required)>'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/lib/scrypt.rb:3:in `<top (required)>'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.5/lib/bundler/runtime.rb:76:in `require'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.5/lib/bundler/runtime.rb:72:in `each'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.5/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.5/lib/bundler/runtime.rb:61:in `each'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.5/lib/bundler/runtime.rb:61:in `require'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.7.5/lib/bundler.rb:133:in `require'
        from /Users/jshepherd/projects/myproject/config/application.rb:12:in `<top (required)>'
        from /Users/jshepherd/projects/myproject/config/environment.rb:2:in `require'
        from /Users/jshepherd/projects/myproject/config/environment.rb:2:in `<top (required)>'
        from /Users/jshepherd/projects/myproject/spec/rails_helper.rb:4:in `require'
        from /Users/jshepherd/projects/myproject/spec/rails_helper.rb:4:in `<top (required)>'
        from /Users/jshepherd/projects/myproject/spec/controllers/api/v1/delivery_events_controller_spec.rb:1:in `require'
        from /Users/jshepherd/projects/myproject/spec/controllers/api/v1/delivery_events_controller_spec.rb:1:in `<top (required)>'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/bin/rspec:23:in `load'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/bin/rspec:23:in `<main>'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/bin/ruby_executable_hooks:15:in `eval'
        from /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by steakknife** [comment]
I would not install the ancient apple gcc formula, it's riddled with security vulnerabilities, it's unmaintained.  If you absolutely have to have gcc, run `brew install gcc`.  But for scrypt, it's unnecessary.

```shell
0 ~ git:master ❯❯❯ gem install scrypt                                             
Fetching: ffi-1.9.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.6
Fetching: ffi-compiler-0.1.3.gem (100%)
Successfully installed ffi-compiler-0.1.3
Fetching: scrypt-2.0.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed scrypt-2.0.0
3 gems installed
0 ~ git:master ❯❯❯ sw_vers                                                  
ProductName:	Mac OS X
ProductVersion:	10.10.1
BuildVersion:	14B25
0 ~ git:master ❯❯❯ ruby -e 'puts RUBY_VERSION'
2.2.0
0 ~ git:master ❯❯❯ which gcc-4.2                                                   
gcc-4.2 not found
1 ~ git:master ❯❯❯
```

(And latest stable Xcode CLT.)

**Comment by tenshiemi** [comment]
Well I spent about 4 hours on this and nothing else worked.

**Comment by steakknife** [comment]
Nuke all gems and Ruby, recompile it.

**Comment by steakknife** [comment]
@tenshiemi Install the latest CLT.  I have 10.10.1, Xcode 6.1.1 and [CLT from here](http://adcdownload.apple.com/Developer_Tools/command_line_tools_os_x_10.10_for_xcode__xcode_6.1.1/commandlinetoolsosx10.10forxcode6.1.1.dmg)

**Comment by steakknife** [comment]
To build multi-architecture gems: `[sudo] env ARCHFLAGS='-m32 -arch i386 -m64 -arch x86_64' gem install scrypt`  (Don't use `sudo`, because problems will follow.)  

```
0 ~ git:master ❯❯❯ file /Library/Ruby/Gems/2.0.0/gems/scrypt-2.0.0/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle
/Library/Ruby/Gems/2.0.0/gems/scrypt-2.0.0/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle: Mach-O universal binary with 2 architectures
/Library/Ruby/Gems/2.0.0/gems/scrypt-2.0.0/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle (for architecture x86_64):	Mach-O 64-bit bundle x86_64
/Library/Ruby/Gems/2.0.0/gems/scrypt-2.0.0/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle (for architecture i386):	Mach-O bundle i386
0 ~ git:master ❯❯❯
```

**Comment by steakknife** [comment]
@jayshepherd Could you run these and post output?

    file `which ruby`
    file /Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle

This can happen when upgrading to a machine because only one architecture was compiled (i386) but the current one needs x86_64.   Removing and recreating the gemset should fix it.

**Comment by jayshepherd** [comment]
This is on a MacBook Pro (Retina, 15-inch, Mid 2014).
Clean install (not an update over Mavericks) of Yosemite currently running 10.10.1 (14B25)

```
/Users/jshepherd/.rvm/rubies/ruby-1.9.3-p547/bin/ruby: Mach-O 64-bit executable x86_64
/Users/jshepherd/.rvm/gems/ruby-1.9.3-p547@myproject/gems/scrypt-2.0.0/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle: Mach-O bundle i386
```

**Comment by steakknife** [comment]
@jayshepherd There's the problem.  64-bit only ruby can't load a 32-bit bundle.

This usually happens if someone copies their home directory (i.e., Migration Assistant) from another machine.  

Either way, I would recreate the gemset.  If that doesn't work, I would consider nuking ~/.rvm and reinstall rubies and gems.  If it persists after that, it might be an rvm issue.

**Comment by jayshepherd** [comment]
This was a clean Yosemite install with no copying of anything. Gemset was created from scratch and all rubies installed.

**Comment by steakknife** [comment]
Post the output of `ls -la` of those files if you would.

—

**Comment by steakknife** [comment]
The ruby binary and the .bundle

—

**Comment by jayshepherd** [comment]
@tenshiemi's solution just worked perfectly for me:

http://sublimecoding.com/blog/2014/10/12/scrypt-gem-native-extension-build-errors/

**Comment by steakknife** [comment]
That installs an ancient and unmaintained gcc that has security vulnerabilities, will break future brew formulas and doesn't solve the underlying issue.

—

**Comment by jayshepherd** [comment]
Is this what you are requesting?

```BASH
➜  bin  ls -la ruby
-rwxr-xr-x  1 jshepherd  staff  9024 Nov 11 20:29 ruby
```

```
✗ ls -la .bundle
total 8
drwxr-xr-x   3 jshepherd  staff   102 Nov 11 23:01 .
drwxr-xr-x  30 jshepherd  staff  1020 Feb 11 11:36 ..
-rw-r--r--   1 jshepherd  staff     8 Nov 11 23:01 config
```

**Comment by steakknife** [comment]
Both look old.  I would nuke ~/.rvm and ~/.gem from orbit, unless you have some massive production environment that has to be supported, update it and rebuild Ruby 2.2.0 from source.  Every time OpenSSL is updated, Ruby should be rebuilt too (because OpenSSL is statically linked in to Ruby by default.).  Script it so you can rebuild your environment cleanly and repeatably, like `~/bin/reinstall_all_rubies`.


I use ruby-install instead of RVM because it compiles production-grade Ruby that usually Just Works.




If you can't get it going, might just setup local dev virtualbox, vagrant, docker and just push to a Linux box if that's what you're deploying to... 12factors'-style develop on what you'd use in production.  Might save some OS X vs. Linux gotchas pain.


—

**Comment by steakknife** [comment]
Also, [here's a hacky, pre-built multi-architecture .bundle](https://gist.github.com/steakknife/fffb9b54d723548c2900) for Ruby 1.9.3 through 2.2.0 inclusive if it's a blocker issue.

**Comment by sikachu** [comment]
@steakknife excuse me for commenting on this old issue.

I'm currently upgrading my client's app to Rails 4.0 and run into an issue installing `scrypt` on El Capitan 10.11.3 and Ruby 1.9.3. I tried the steps above to see if I could force it to compile x86_64 binary, but seems like it didn't want to.

```
[~] rvm use 1.9.3
Using /Users/sikachu/.rvm/gems/ruby-1.9.3-p551
[~] gem install scrypt
Fetching: ffi-1.9.10.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.10
Fetching: ffi-compiler-0.1.3.gem (100%)
Successfully installed ffi-compiler-0.1.3
Fetching: scrypt-2.1.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed scrypt-2.1.1
3 gems installed
[~] file ~/.rvm/gems/ruby-1.9.3-p551/gems/scrypt-2.1.1/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle
/Users/sikachu/.rvm/gems/ruby-1.9.3-p551/gems/scrypt-2.1.1/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle: Mach-O bundle i386
[~] gem uninstall -ax scrypt ffi-compiler ffi  
Successfully uninstalled scrypt-2.1.1
Successfully uninstalled ffi-compiler-0.1.3
Successfully uninstalled ffi-1.9.10
[~] env ARCHFLAGS='-m32 -arch i386 -m64 -arch x86_64' gem install scrypt
Fetching: ffi-1.9.10.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.10
Fetching: ffi-compiler-0.1.3.gem (100%)
Successfully installed ffi-compiler-0.1.3
Fetching: scrypt-2.1.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed scrypt-2.1.1
3 gems installed
[~] file ~/.rvm/gems/ruby-1.9.3-p551/gems/scrypt-2.1.1/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle
/Users/sikachu/.rvm/gems/ruby-1.9.3-p551/gems/scrypt-2.1.1/ext/scrypt/x86_64-darwin/libscrypt_ext.bundle: Mach-O bundle i386
[~] file `which ruby`
/Users/sikachu/.rvm/rubies/ruby-1.9.3-p551/bin/ruby: Mach-O 64-bit executable x86_64
```

I'm thinking about trying to use your binary in your previous comment for now, but I just want to reach out first in case I'm missing something. Thank you.

**Comment by steakknife** [comment]
[Ruby 1.9.3 is unsupported](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/) and insecure, [don't use it](https://www.ruby-lang.org/en/downloads/)... upgrade that **first** to the latest stable (currently 2.3.0).  Don't build universal binaries because it just causes unnecessary problems. For [properly installed](https://www.ruby-lang.org/en/documentation/installation/#ruby-install) Ruby, no magic environment variables are needed. I only use and recommend [chruby](https://github.com/postmodern/chruby)+[ruby-install](https://github.com/postmodern/ruby-install), use anything else at your own, unsupported peril.
 
```
0 ~ git:master ❯❯❯ file `which ruby`                                                                                                                                           ✖ ✱ ◼
/usr/local/ruby/ruby-2.3.0/bin/ruby: Mach-O 64-bit executable x86_64
0 ~ git:master ❯❯❯ gem uninstall -Iax scrypt                                                                                                                                   ✖ ✱ ◼
Successfully uninstalled scrypt-2.1.1
0 ~ git:master ❯❯❯ gem install scrypt                                                                                                                                          ✖ ✱ ◼
Fetching: scrypt-2.1.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed scrypt-2.1.1
1 gem installed
0 ~ git:master ❯❯❯ cat ~/.bundle/config                                                                                                                                        ✖ ✱ ◼
---
BUNDLE_BUILD__RKERBEROS: "--with-rkerberos-dir=/usr/local/opt/krb5"
0 ~ git:master ❯❯❯ cat ~/.gemrc                                                                                                                                                ✖ ✱ ◼
---
gem: --no-document
0 ~ git:master ❯❯❯ gem env                                                                                                                                                   ⏎ ✖ ✱ ◼
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.2
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: {{redacted}}/.gem/ruby/2.3.0
  - USER INSTALLATION DIRECTORY: {{redacted}}/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/ruby/ruby-2.3.0/bin/ruby
  - EXECUTABLE DIRECTORY: {{redacted}}/.gem/ruby/2.3.0/bin
  - SPEC CACHE DIRECTORY: {{redacted}}/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/ruby/ruby-2.3.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - {{redacted}}/.gem/ruby/2.3.0
     - /usr/local/ruby/ruby-2.3.0/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - {{redacted}}/.gem/ruby/2.3.0/bin
     - /usr/local/ruby/ruby-2.3.0/lib/ruby/gems/2.3.0/bin
     - /usr/local/ruby/ruby-2.3.0/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /bin
     - /usr/local/MacGPG2/bin
     - /Library/TeX/texbin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - {{redacted}}/bin
     - {{redacted}}/perl5/bin
     - /usr/local/go/bin
     - {{redacted}}/.go/bin
     - {{redacted}}/.node/bin
0 ~ git:master ❯❯❯
```

**Comment by sikachu** [comment]
@steakknife I hear you loud and clear. We just want to minimize risk on doing Rails/Ruby upgrade at the same time. I ended up just lock Authlogic to the version that doesn't require scrypt (since we're using bcrypt anyway) to mitigate the issue.

Can't wait for upgrading this project to Rails 4.2/Ruby 2.3, but it is what it is. We just have to do this step by step ...

**Comment by steakknife** [comment]
@sikachu Many shops are still running 1.8.7 (MRI/REE) in production.  Maintenance/support of 10k-100k's of customer boxes and dozens-hundreds of apps... tiny differences break everything.  Especially hourly billings without milestones, just always look insanely busy when on-site. ;)

**Comment by brendon** [comment]
@steakknife, I'm having this exact error with El Capitan. I'm using 1.9.3, and can't migrate away from it at this point though it's in the plans. This is a fresh install, brand new install of ruby, clean gemset.

Do you have any other pointers as to why bundle/gem might be compiling this wrong?

**Comment by steakknife** [comment]
Don't use RVM, it's pseudo mconvenience at the expense of stability. Follow
recommendations above because your Ruby build,
gem/bundler config, environment variables or something else is
misconfigured.  Check ~/.gemrc ~/.gem/ and ~/.bundlle/

**Comment by brendon** [comment]
Thanks for that. Yea I've been feeling more and more uncomfortable about RVM lately. I don't use it in production (ruby-build instead) so I should probably make the transition.

**Comment by stakach** [comment]
Please re-open this issue if you have any issues with the latest release v3.0.0

**Comment by brendon** [comment]
Thanks @stakach, my issue was resolved by ditching RVM and using rbenv instead.
