### ISSUE TITLE
can't build scrypt in Archlinux

### ISSUE THREAD

**Issue by zerosign** [pbhogan/scrypt#59]
With :

```
 scrypt git:(master) ✗ gcc --version
gcc (GCC) 6.1.1 20160802
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ldd (GNU libc) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
and ruby-2.3.1, I can't build this gem.

```
 scrypt git:(master) ✗ rake compile_ffi
gcc -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -fPIC   -o ext/scrypt/x86_64-linux/scryptenc_cpuperf.o -c ext/scrypt/scryptenc_cpuperf.c
ext/scrypt/scryptenc_cpuperf.c:105:21: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
 getclocktime(struct timespec * ts)
                     ^~~~~~~~
ext/scrypt/scryptenc_cpuperf.c: In function ‘getclocktime’:
ext/scrypt/scryptenc_cpuperf.c:111:4: error: dereferencing pointer to incomplete type ‘struct timespec’
  ts->tv_sec = tv.tv_sec;
    ^~
ext/scrypt/scryptenc_cpuperf.c: At top level:
ext/scrypt/scryptenc_cpuperf.c:119:21: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
 getclockdiff(struct timespec * st, double * diffd)
                     ^~~~~~~~
ext/scrypt/scryptenc_cpuperf.c: In function ‘getclockdiff’:
ext/scrypt/scryptenc_cpuperf.c:121:18: error: storage size of ‘en’ isn’t known
  struct timespec en;
                  ^~
ext/scrypt/scryptenc_cpuperf.c:125:27: error: dereferencing pointer to incomplete type ‘struct timespec’
  *diffd = (en.tv_nsec - st->tv_nsec) * 0.000000001 +
                           ^~
ext/scrypt/scryptenc_cpuperf.c:121:18: warning: unused variable ‘en’ [-Wunused-variable]
  struct timespec en;
                  ^~
ext/scrypt/scryptenc_cpuperf.c: In function ‘scryptenc_cpuperf’:
ext/scrypt/scryptenc_cpuperf.c:139:18: error: storage size of ‘st’ isn’t known
  struct timespec st;
                  ^~
ext/scrypt/scryptenc_cpuperf.c:139:18: warning: unused variable ‘st’ [-Wunused-variable]
rake aborted!
Command failed with status (1): [gcc -fexceptions -O -fno-omit-frame-pointe...]
/home/zerosign/.rvm/gems/ruby-2.3.1@scrypt/gems/ffi-compiler-1.0.1/lib/ffi-compiler/compile_task.rb:133:in `block (2 levels) in define_task!'
/home/zerosign/.rvm/gems/ruby-2.3.1@scrypt/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/zerosign/.rvm/gems/ruby-2.3.1@scrypt/bin/ruby_executable_hooks:15:in `eval'
/home/zerosign/.rvm/gems/ruby-2.3.1@scrypt/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => compile_ffi => ffi-compiler:default => ext/scrypt/x86_64-linux/libscrypt_ext.so => ext/scrypt/x86_64-linux/scryptenc_cpuperf.o
(See full trace by running task with --trace)
```

It seems that either current *libc header* are being altered.

**Comment by stakach** [comment]
Thanks for the patch. I've cut a new release v3.0.2

**Comment by stakach** [comment]
I've cut a new release v3.0.3
Let me know if it works for you - thanks

**Comment by zerosign** [comment]
It works, thanks :+1:

**Comment by cmatheson** [comment]
I'm a very similar compilation error on ruby-2.4 / gcc 6.3.1:

```gcc -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -D__need_timespec -fPIC   -o x86_64-linux/scryptenc_cpuperf.o -c ./scryptenc_cpuperf.c
./scryptenc_cpuperf.c:105:21: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
 getclocktime(struct timespec * ts)
                     ^~~~~~~~
./scryptenc_cpuperf.c: In function ‘getclocktime’:
./scryptenc_cpuperf.c:111:4: error: dereferencing pointer to incomplete type ‘struct timespec’
  ts->tv_sec = tv.tv_sec;
    ^~
./scryptenc_cpuperf.c: At top level:
./scryptenc_cpuperf.c:119:21: warning: ‘struct timespec’ declared inside parameter list will not be visible outside of this definition or declaration
 getclockdiff(struct timespec * st, double * diffd)
                     ^~~~~~~~
./scryptenc_cpuperf.c: In function ‘getclockdiff’:
./scryptenc_cpuperf.c:121:18: error: storage size of ‘en’ isn’t known
  struct timespec en;
                  ^~
./scryptenc_cpuperf.c:125:27: error: dereferencing pointer to incomplete type ‘struct timespec’
  *diffd = (en.tv_nsec - st->tv_nsec) * 0.000000001 +
                           ^~
./scryptenc_cpuperf.c:121:18: warning: unused variable ‘en’ [-Wunused-variable]
  struct timespec en;
                  ^~
./scryptenc_cpuperf.c: In function ‘scryptenc_cpuperf’:
./scryptenc_cpuperf.c:139:18: error: storage size of ‘st’ isn’t known
  struct timespec st;
                  ^~
./scryptenc_cpuperf.c:139:18: warning: unused variable ‘st’ [-Wunused-variable]
rake aborted!
Command failed with status (1): [gcc -fexceptions -O -fno-omit-frame-pointe...]
/home/cameron/.gem/ruby/2.4.0/gems/ffi-compiler-1.0.1/lib/ffi-compiler/compile_task.rb:133:in `block (2 levels) in define_task!'
Tasks: TOP => default => x86_64-linux/libscrypt_ext.so => x86_64-linux/scryptenc_cpuperf.o
(See full trace by running task with --trace)

rake failed, exit code 1
```
As you can see, the D__need_timespec flag is present.  I can make this thing build by changing -std=c99 to -std=gnu99 (specs still pass), but I'm not sure if that's an acceptable solution

**Comment by tarnacious** [comment]
This didn't work for me either, same error.

My system:

```
$ uname -a
Linux arch-macbook 4.10.2-1-ARCH #1 SMP PREEMPT Mon Mar 13 17:13:41 CET 2017 x86_64 GNU/Linux
$ gcc --version
gcc (GCC) 6.3.1 20170306
```

I could also get this to compile using `-std=gnu99`. I could also get this compiling with `-std=c99` by replacing `-D__need_timespec` with `-D_POSIX_C_SOURCE=199309L` which I found referenced [here](https://gcc.gnu.org/ml/gcc-help/2004-02/msg00098.html).

(Defining `timespec` as done [here for MINGW32](https://github.com/pbhogan/scrypt/blob/master/ext/scrypt/scryptenc_cpuperf.c#L42) also worked, but this should be defined by POSIX apparently so I think the compiler flag is better)

**Comment by abartov** [comment]
So, can this be packaged into a new version of the gem?
