### ISSUE TITLE
argument error in FFI

### ISSUE THREAD

**Issue by jondavidchristopher** [pbhogan/scrypt#70]
When trying to require scrypt on my system I am getting the following error:

ArgumentError: wrong number of arguments (given 1, expected 2+)

STACK TRACE:

/Users/jc/.rubies/ruby-2.5.0/lib/ruby/2.5.0/mkmf.rb:1243:in `find_type'
ffi (1.9.21) lib/ffi/struct.rb:332:in `find_type'
ffi (1.9.21) lib/ffi/struct.rb:326:in `find_field_type'
ffi (1.9.21) lib/ffi/struct.rb:366:in `array_layout'
ffi (1.9.21) lib/ffi/struct.rb:278:in `layout'
scrypt (3.0.5) lib/scrypt.rb:140:in `<class:Calibration>'
scrypt (3.0.5) lib/scrypt.rb:139:in `<class:Engine>'
scrypt (3.0.5) lib/scrypt.rb:24:in `<module:SCrypt>'
scrypt (3.0.5) lib/scrypt.rb:10:in `<top (required)>'

![image](https://user-images.githubusercontent.com/1843437/36514024-4604957a-1727-11e8-9aa5-38e7522e059e.png)

Any bright ideas here? I am coming up against a wall with this one.

**Comment by jondavidchristopher** [comment]
bumping down to 3.0.4 solved this issue.
